Patch 5: Updates Website
Scratch-Bookmarklets/Scratch-Bookmarklets.github.io pull request #127
Opened 2021-05-25 20:34 UTC by xItzDiamondx

**Resolves**

Resolves none

**Changes**

I made the website a bit better
**Reason for changes**

**Tests**
I have tested on my fork

2021-05-25 20:46 UTC, FunctionalMetatable commented
please make new branches for pr'ing. the commit history is very long

2021-05-26 00:41 UTC, gosoccerboy5 commented
> please make new branches for pr'ing. the commit history is very long

Agreed. In addition, develop locally with [Github Desktop](//desktop.github.com) if possible, and make sure to squash and merge when merging PR with many commits

2021-05-26 00:47 UTC, xItzDiamondx commented
I had GHD but I deleted it because my PC was running too slowly. I do use
VS Code and test locally though.

On Tue, May 25, 2021 at 7:41 PM gosoccerboy5 ***@***.***>
wrote:

> please make new branches for pr'ing. the commit history is very long
>
> Agreed. In addition, develop locally with Github Desktop
> <//desktop.github.com> if possible, and make sure to squash and merge
> when merging PR with many commits
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/pull/127#issuecomment-848373875>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATNX7MF7KQH5M4PAIFKUNCDTPQ7S5ANCNFSM45QFBZHA>
> .
>

2021-05-26 11:28 UTC, Shluffy requested changes

2021-05-26 11:28 UTC, Shluffy commented on contributors.html
> +  <div align=center>
Pls change this to above the `ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section `

2021-05-26 11:41 UTC, Shluffy requested changes

2021-05-26 11:41 UTC, Shluffy commented on contributors.html
> +  </div>
again, this should be outside of the all-contributors stuff

2021-05-26 11:42 UTC, Shluffy commented
otherwise, everything looks good.

2021-05-26 16:14 UTC, Shluffy commented
This only solves the problem on the contributors page, not on all of them.

2021-05-26 20:10 UTC, Shluffy commented
the purpose of this pr has already been fixed.

2021-05-26 21:19 UTC, xItzDiamondx commented
it has a few more patches so ima merge

On Wed, May 26, 2021 at 3:11 PM ShluffyMonster ***@***.***>
wrote:

> Closed #127
> <https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/pull/127>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/pull/127#event-4801719889>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATNX7MEUGR2ELM444G2PFJDTPVIVJANCNFSM45QFBZHA>
> .
>

2021-05-26 21:30 UTC, xItzDiamondx reviewed
Fixed

2021-05-26 22:00 UTC, Shluffy approved these changes
looks good. there doesn't seem to be any merge conflicts so I will merge.

2021-05-26 22:01 UTC, merged