Patch 1: Updates
Scratch-Bookmarklets/Scratch-Bookmarklets.github.io pull request #193
Opened 2021-07-06 14:57 UTC by NotDiamondZ

**Resolves**

Resolves none

**Changes**

I've added some files. There is a bug, but I will fix that. Do not merge.
**Reason for changes**

IDK
**Tests**

Tested locally.

2021-07-06 20:13 UTC, FunctionalMetatable commented
I'm sure this doesn't change **anything** related to prettier..

2021-07-06 20:22 UTC, NotDiamondZ commented
It does. Just merge when I'm ready.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Tuesday, July 6th, 2021 at 3:13 PM, FunctionalMetatable ***@***.***> wrote:

> I'm sure this doesn't change anything related to prettier..
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, [view it on GitHub](https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/pull/193#issuecomment-875050977), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AT4QEOJPPCOZ4GCEH4ZMUJDTWNPYDANCNFSM474YAK6A).

2021-07-06 20:22 UTC, NotDiamondZ commented
There was a conflict, I resolved it. I removed the bug that was making Prettier fail.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On Tuesday, July 6th, 2021 at 3:13 PM, FunctionalMetatable ***@***.***> wrote:

> I'm sure this doesn't change anything related to prettier..
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, [view it on GitHub](https://github.com/Scratch-Bookmarklets/Scratch-Bookmarklets.github.io/pull/193#issuecomment-875050977), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AT4QEOJPPCOZ4GCEH4ZMUJDTWNPYDANCNFSM474YAK6A).

2021-07-08 23:08 UTC, xItzDiamondx commented
Ima merge

2021-07-08 23:09 UTC, xItzDiamondx commented
If Shluffy approves

2021-07-09 23:15 UTC, Shluffy requested changes

2021-07-09 23:15 UTC, Shluffy commented on 404.html
> +  <title>404 - Scratch Bookmarklets</title>
thoughts on this anybody?

2021-07-09 23:15 UTC, Shluffy commented on assets/json/package.json
> +    "brourbeinsus",
pls use only 1

2021-07-09 23:15 UTC, Shluffy commented on bookmarklets.html
> -    <script src="assets/js/script.js"
this? removed here but not on other pages?

2021-07-09 23:15 UTC, Shluffy commented on README.md
>  <!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
maybe don't remove

2021-07-09 23:15 UTC, Shluffy commented on README.md
>  <!-- ALL-CONTRIBUTORS-BADGE:START - Do not remove or modify this section -->
or change

2021-07-09 23:15 UTC, Shluffy commented on README.md
> +<h2>See the site LIVE at our website; <a href="https://bit.ly/ScratchBookmarklets" title="Website">Scratch Bookmarklets</a></h2>
remove live pls

2021-07-13 19:13 UTC, NotDiamondZ commented on assets/json/package.json
> +    "brourbeinsus",
ok

2021-07-13 19:14 UTC, NotDiamondZ commented on 404.html
> +  <title>404 - Scratch Bookmarklets</title>
that is so it works with microsoft edge and ie. it is automated in vs code

2021-08-15 18:53 UTC, closed without merging